apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      type: frontend-nginx-pod

  template:
    metadata:
      name: nginx-pod
      labels:
        type: frontend-nginx-pod
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx      
          ports:
            - containerPort: 8080  
